import "./globals.css";
import { Open_Sans } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={openSans.className}>
      <body>
        <header className="sticky top-0 bg-white dark:bg-slate-950 z-10">
          <Navbar />
        </header>
        <main className="dark:flex w-full dark:bg-slate-950">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
