import "./globals.css";
import { Open_Sans } from "next/font/google";
import Navbar from "./components/Navbar";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={openSans.className}>
      <body className="w-full bg-white dark:bg-slate-900 overflow-auto">
        <header className="sticky top-0 bg-white  dark:bg-slate-900 z-10 border-b">
          <div className="max-w-screen-2xl mx-auto">
            <Navbar />
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
